### ISSUE TITLE
静的解析 Cascade consecutive method invocations on the same reference

### ISSUE THREAD

**Issue by Xx0w0wxX** [Xx0w0wxX/manameme#5]
> Cascade consecutive method invocations on the same reference

**Comment by Xx0w0wxX** [comment]
- https://makicamel.hatenablog.com/entry/2019/03/27/184508

rubyとか知らんし

**Comment by Xx0w0wxX** [comment]
https://github.com/dart-lang/sdk/issues/30682

**Comment by Xx0w0wxX** [comment]
https://stackoverflow.com/questions/17025769/how-do-method-cascades-work-exactly-in-dart

ここでも...

**Comment by mono0926** [comment]
もし以下を読んでも分からなければ回答します :octocat: 
https://dart-lang.github.io/linter/lints/cascade_invocations.html

**Comment by Xx0w0wxX** [comment]
解決しました
